### ISSUE TITLE
The Python implementation of object.__getattribute__ does not detect descriptors correctly

### ISSUE THREAD

**Issue by maggyero** [brettcannon/desugar#4]
From your Python implementation of `object.__getattribute__` in your blog article [*Unravelling attribute access in Python*](https://snarky.ca/unravelling-attribute-access-in-python/):

```python
class object:
    def __getattribute__(self: Any, attr: str) -> Any:
        # […]
        for base in self_type.mro():
            if attr in base.__dict__:
                type_attr = base.__dict__[attr]
                type_attr_type = type(type_attr)
                # MISSING FOR-LOOP: for attr_base in type_attr_type.mro():
                if "__get__" in type_attr_type.__dict__:
                    descriptor_type_get = type_attr_type.__dict__["__get__"]
                    # Include/descrobject.h:PyDescr_IsData
                    if "__set__" in type_attr_type.__dict__:
                        # Data descriptor.
                        return descriptor_type_get(type_attr, self, self_type)
                    else:
                        break  # Non-data descriptor.
                else:
                    break  # Plain object.
        # […]
```

So you correctly look up an attribute named `attr` in the types of the `mro()` of `self_type`. However you don’t look up a method `__get__` in all the types of the `mro()` of the found attribute’s type but only in the found attribute’s type. In other words, *you ignore the base types of the found attribute’s type*.

Consequently, your Python implementation fails to behave as expected below by considering `foo` as a plain object instead of a non-data descriptor:

```python
>>> class A:
...     def __get__(self, instance, owner):
...         return 'bar'
... 
>>> class B(A):
...     pass
... 
>>> class C:
...     foo = B()
... 
>>> C().foo
'bar'  # Your implementation returns '<__main__.B object at 0x101d26d60>' instead.
```

To fix this you should also loop on `type_attr_type.mro()` in your Python implementation (cf. my comment MISSING FOR-LOOP above).

**Comment by brettcannon** [comment]
Fixed in https://github.com/brettcannon/desugar/commit/2661c22263f0b63c2f3ad1630a0195120e23d750.

**Comment by maggyero** [comment]
Thanks!
