### ISSUE TITLE
Should decorators remain sugary?

### ISSUE THREAD

**Issue by pylang** [brettcannon/desugar#5]
There is likely a rationale that escapes me, but I noticed decorators were not mentioned in the README.  It's the first thing that comes to mind when I think of syntactic sugar.  Though, I realize the `@` symbol here may not quite fit in your categories.  Are decorators intentionally excluded?

Also, are you excluding `with/as` and `except/as`?

Btw, I'm enjoying the [blogs](https://snarky.ca/tag/syntactic-sugar/).  Thanks.

**Comment by brettcannon** [comment]
@pylang Decorators were left off by accident when I handled `@` for matrix multiplication. I have now added them back in.

As for `with`/`as` and `except`/`as`, those are covered by `with` and `except`. I only list multiple parts to a syntax when it is composed of multiple blocks (e.g. `if`/`elif`) and the `as` clauses of those two statements don't influence blocks.
