### ISSUE TITLE
Errors in "Unravelling `elif`/`else` from `if` statements" post

### ISSUE THREAD

**Issue by itamaro** [brettcannon/desugar#6]
I'm referring to [this post](https://snarky.ca/unravelling-elif-else-from-if-statements/) - couldn't find the actual source for the post (and the error don't show up in this repo), so sorry if this is not the right place to report :-) 

towards the end, the last example is:

```
if a:
    b
elif c:
    d
elif e:
    f
else:
    g
```

which should become:

```
_b_ran = _d_ran = _f_ran = False
if a:
    _b_ran = True
    b
if not _b_ran and c:
    _d_ran = True
    d
if not (_b_ran or _d_ran) and e:
    _f_ran = True
    f
if not (_b_ran or _d_ran or _f_ran):
    g
```

as opposed to what's currently on the post:

```
_b_ran = _d_ran = _f_ran = False
if a:
    _b_ran = True
    b
if not _b_ran and c:
    _d_ran = True
if not (_b_ran or _d_ran) and e:
    _g_ran = True
if not (_b_ran or _d_ran or _f_ran):
    g
```

Thanks for writing this series - it's super interesting and informative!

**Comment by brettcannon** [comment]
This works well enough (otherwise Twitter also works).

And thanks for letting me know! The post is now updated. Looks like my last-minute update to that code sample didn't quite work out. 😅
