### ISSUE TITLE
Unravelling `finally` from `try` statements

### ISSUE THREAD

**Issue by icemac** [brettcannon/desugar#7]
In https://snarky.ca/unravelling-finally-and-else-from-try/ you wrote:

```python
try:
    A
except Exception:
    B
finally:
    C
```

> Example try statement with a finally clause
we can transform it into:

```python
try:
    try:
        A
    except Exception:
        B
except BaseException:
    C
    raise
C
```

Could it be that this transformation is not entirely correct?

Given:

```python
def f(n):
    try:
        return 1/n
    except Exception:
        print('except')
    finally:
        print('finally')
```

Calling this function gives the following results depending whether an exception was raised or not:

```python
>>> print(f(1))
finally
1.0
>>> print(f(0))
except
finally
None
```

Transforming the function as suggested in the blog post I get:

```python
def g(n):
    try:
        try:
            return 1/n
        except Exception:
            print('except')
    except BaseException:
        print('finally')
        raise
    print('finally')
```

Calling this function I get different results:

```python
>>> print(g(1))
1.0
>>> print(g(0))
except
finally
None
```

So in case no exception is raised the finally part of the transformed function is not called.

Am I missing something here or did I make a mistake in the transformation?

**Comment by brettcannon** [comment]
I didn't cover/plan for a `return` in the `try` block. 😅 I have added an explainer at the end of the post now, but to deal with `return` you either need to postpone the execution of `return` or inline the `finally` block.
